services:
  mongodb:
    image: mongo:7.0
    container_name: vibeton_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: vibeton_game
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - vibeton_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vibeton_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/vibeton_game?authSource=admin
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=true
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - vibeton_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vibeton_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - vibeton_network

  nginx:
    image: nginx:alpine
    container_name: vibeton_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - vibeton_network

volumes:
  mongodb_data:

networks:
  vibeton_network:
    driver: bridge 